### ISSUE TITLE
请您稍微介绍一下您的测试文件以及使用方法

### ISSUE THREAD

**Issue by ConanMusk** [xl-tang3/RCOT#1]
我想知道您的代码中这三个文件的作用：

![image](https://github.com/xl-tang3/RCOT/assets/67884112/e166ece4-83fc-4525-a25f-826d1bc9350e)

**Comment by xl-tang3** [comment]
感谢关注。使用的话修改args对应的文件路径就可以
第一个noise是用于测试去除高斯噪声的，会涉及添加随机的高斯噪声。
第二个和第三个把退化图像和清晰图像放到对应路径下，运行即可。第二个会对大小不匹配的图像进行一个resize
