### ISSUE TITLE
Train Code

### ISSUE THREAD

**Issue by hhhhhhalf** [xl-tang3/RCOT#2]
Hello, thank you very much for your excellent work. Now I want to reproduce your code to learn, but it seems that the code is incomplete. Is it convenient for you to upload the complete code? Thank you

**Comment by xl-tang3** [comment]
Hi, the train code is trainer.py, and you can follow the setting instructions to use it.

**Comment by hhhhhhalf** [comment]
Okay, thank you very much.

**Comment by codeMakerZWH** [comment]
from util.dataset_utils import TrainDataset                 trainer.py第十三行  util是不是代码本地包  没有找到这个util类

**Comment by xl-tang3** [comment]
是的，最近更新完上传漏了，感谢指出，已上传
