### ISSUE TITLE
Questions about unpaired training

### ISSUE THREAD

**Issue by weijinbao1998** [xl-tang3/RCOT#6]
Hi, thank you for sharing the code of your excellent paper!

How can I realize unpaired training according to existing trainer.py？Or just randomly shuffle the target x and degraded input y like (rain001.png, norain002.png as paired data to train the network)?

Thank you!

**Comment by xl-tang3** [comment]
Yes, you may just set the parameter "pairnum" to be 0 for unpaired.

**Comment by weijinbao1998** [comment]
In trainer.py, this code（ train_set = DegTarDataset(deg_path, tar_path, pairnum=opt.pairnum) ） can not be directly ran. Becasue i can not find the DegTarDataset class.

**Comment by xl-tang3** [comment]
I guess using "train_set = TrainDataset(opt)" would be ok.



At 2024-12-10 20:51:16, "Jinbao Wei" ***@***.***> wrote:

In trainer.py, this code（ train_set = DegTarDataset(deg_path, tar_path, pairnum=opt.pairnum) ） can not be directly ran. Becasue i can not find the DegTarDataset class.

**Comment by weijinbao1998** [comment]
Thanks for your reply! It works.

**Comment by weijinbao1998** [comment]
@

**Comment by weijinbao1998** [comment]
Hi, i find even if pairnum=0 , we still need paired target to train Fnet. So in unpaired setting, are we set the target unpaired beforehand to train Fnet?

**Comment by xl-tang3** [comment]
'Fnet' computes the potential value by taking targets in the target domain, which are not required to be paired with the input degraded data.

**Comment by weijinbao1998** [comment]
Thanks for your patient reply!
